### ISSUE TITLE
[REQ] AME Playbook

### ISSUE THREAD

**Issue by MarcoRavich** [EternityOS/Eternity#1]
Hi there, thanks for this really cool project !

As many other [Windows-customs](https://github.com/MarcoRavich/Opendows#open-source-customized-windows-isos) have already done, I strongly suggest to release an [Playbook](https://docs.ameliorated.io/playbooks.html) version trough [AME Wizard](https://ameliorated.io/) too.

Hope that inspires !

**Comment by instead1337** [comment]
Hi, but you should check our new playbook named like RapidOS, you can find it on [Github](https://github.com/rapid-community/RapidOS)

**Comment by instead1337** [comment]
And thank you for adding our playbook in your github repository, that's inspires!

**Comment by MarcoRavich** [comment]
Hi there, thanks for reply.

Just added RaidOS to my [Opendows repo](https://forart.it/opendows/) !

I'm discussing with @mewostick about a contents creators-oriented playbook at [Creosynth](https://github.com/mewostick/Creosynth#readme): https://github.com/mewostick/Creosynth/discussions/1

Hope to establish some kind of collaboration !
